name: Deploy to FTP

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubumtu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                node-version: 14.21.2
            
            - name: Install dependencies nd build Nextjs app
              run: |
                npm install
                npm build

            - name: Deploy via FTP
              run: |
                lftp -e "open -u ${{ secrets.FTP_USERNAME }}, ${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_HOST }}; set ssl:verify-certificate; mirror -R -e -x .git/ -x .github/ -x .next/ -x node_modules/ . /public_html/; bye"